writer:
  _target_: src.logger.WandBWriter
  project_name: retail_testing
  entity: null
  run_name: testing
  mode: online
  loss_names:
  - loss
  log_checkpoints: false
  id_length: 8
  run_id: e45wd0ob
metrics:
  train: []
  inference:
  - _target_: src.metrics.Accuracy
    name: accuracy
  - _target_: src.metrics.AUC_ROC
    name: roc-auc
datasets:
  train:
    _target_: src.datasets.StreamRetailDataset
    file_path: /Users/andreypetukhov/Documents/work-related/LightFM/data/test_dataset.csv
    dt_features:
    - user_inn_dt_id
    - user_total_views_id
    - user_unique_items_id
    - user_total_transactions_id
    kt_features:
    - item_inn_kt_id
    - item_categoryid_id
    - item_available_id
    label_column: label
    chunk_size: 5000
  val:
    _target_: src.datasets.StreamRetailDataset
    file_path: /Users/andreypetukhov/Documents/work-related/LightFM/data/test_dataset.csv
    dt_features:
    - user_inn_dt_id
    - user_total_views_id
    - user_unique_items_id
    - user_total_transactions_id
    kt_features:
    - item_inn_kt_id
    - item_categoryid_id
    - item_available_id
    label_column: label
    chunk_size: 5000
dataloader:
  _target_: torch.utils.data.DataLoader
  batch_size: 16
  num_workers: 1
transforms:
  batch_transforms: {}
  instance_transforms: {}
model:
  _target_: src.models.DeepFM
  embed_dim: 8
optimizer:
  _target_: torch.optim.AdamW
  lr: 0.0003
lr_scheduler:
  _target_: torch.optim.lr_scheduler.OneCycleLR
  max_lr: 0.0005
  pct_start: 0.1
  epochs: ${trainer.n_epochs}
  anneal_strategy: cos
loss_function:
  _target_: src.loss.LogitsBCELoss
trainer:
  log_step: 2
  n_epochs: 20
  device_tensors:
  - user
  - item
  - label
  resume_from: null
  device: auto
  override: true
  monitor: min val_loss
  save_period: 5
  early_stop: ${trainer.n_epochs}
  save_dir: deepspeech2
  seed: 1
  max_grad_norm: 10
