spark:
  appName: "Andrey-DataGen-18"
  master: "yarn"
  executor_instances: "6"
  executor_cores: "15"
  driver_memory: "20g"
  executor_memory: "64g"
  executor_memoryOverhead: "16g"
dates:
  train_date_start: "2024-10-01"
  train_date_end: "2024-12-01"
  test_date_start: "2024-12-02"
  test_date_end: "2024-12-08"
outputs:
  data_dir: "data_18"
  save_schema: "arnsdpsbx_t_team_fin_adviser"
  train_name: "deepfm_train_18"
  test_name: "deepfm_test_18"
  log_file: "app.log"
