train:
  _target_: src.datasets.StreamDataset
  file_path: /home/datalab/nfs/deepfm/data/train_11_coalesced/train_2024-10-01_2024-10-19.parquet
  # passed as list
  dt_features:
    - "inn_dt_index"
    - "dt_okved_index"
    - "dt_okato_index"
    - "dt_bic_34_index"
    - "dt_bic_56_index"
    - "dt_bic_79_index"
    - "dt_num_13_index"
    - "dt_num_45_index"
    - "dt_num_68_index"
    - "dt_buyers_count_index"
  kt_features:
    - "inn_kt_index"
    - "kt_okved_index"
    - "kt_okato_index"
    - "kt_bic_34_index"
    - "kt_bic_56_index"
    - "kt_bic_79_index"
    - "kt_num_13_index"
    - "kt_num_45_index"
    - "kt_num_68_index"
    - "kt_buyers_count_index"
  kt_double_features:
    - "kt_avg_sum"
    - "kt_stddev_sum"
    - "kt_min_sum"
    - "kt_max_sum"
    - "kt_median_sum"
    - "kt_skewness_sum"
    - "kt_entropy"
    - "kt_normalized_entropy"
  dt_double_features:
    - "dt_avg_sum"
    - "dt_stddev_sum"
    - "dt_min_sum"
    - "dt_max_sum"
    - "dt_median_sum"
    - "dt_skewness_sum"
    - "dt_entropy"
    - "dt_normalized_entropy"
  label_column: "label"
  chunk_size: 4096

val:
  _target_: src.datasets.StreamDataset
  file_path: /home/datalab/nfs/deepfm/data/train_11_coalesced/test_2024-10-20_2024-10-22.parquet
  dt_features:
    - "inn_dt_index"
    - "dt_okved_index"
    - "dt_okato_index"
    - "dt_bic_34_index"
    - "dt_bic_56_index"
    - "dt_bic_79_index"
    - "dt_num_13_index"
    - "dt_num_45_index"
    - "dt_num_68_index"
    - "dt_buyers_count_index"
  kt_features:
    - "inn_kt_index"
    - "kt_okved_index"
    - "kt_okato_index"
    - "kt_bic_34_index"
    - "kt_bic_56_index"
    - "kt_bic_79_index"
    - "kt_num_13_index"
    - "kt_num_45_index"
    - "kt_num_68_index"
    - "kt_buyers_count_index"
  kt_double_features:
    - "kt_avg_sum"
    - "kt_stddev_sum"
    - "kt_min_sum"
    - "kt_max_sum"
    - "kt_median_sum"
    - "kt_skewness_sum"
    - "kt_entropy"
    - "kt_normalized_entropy"
  dt_double_features:
    - "dt_avg_sum"
    - "dt_stddev_sum"
    - "dt_min_sum"
    - "dt_max_sum"
    - "dt_median_sum"
    - "dt_skewness_sum"
    - "dt_entropy"
    - "dt_normalized_entropy"
  label_column: "label"
  chunk_size: 4096