train: [] # metrics that are calculated during training
inference: # metrics that are calculated during inference (eval)
  - _target_: src.metrics.Accuracy
    name: "accuracy" # it is better to avoid spaces in names
  - _target_: src.metrics.AUC_ROC
    name: "roc-auc"
