defaults:
  - writer: tensorboard
  - metrics: no_metrics
  - datasets: transactions_21
  - dataloader: default
  - transforms: example
  - model: deepfm
  - _self_

data:
  user_feature_sizes_path: /home/datalab/nfs/deepfm/data/train_21/user_feature_sizes.json
  item_feature_sizes_path: /home/datalab/nfs/deepfm/data/train_21/item_feature_sizes.json

optimizer:
  _target_: torch.optim.AdamW
  lr: 3e-4

lr_scheduler:
  _target_: torch.optim.lr_scheduler.OneCycleLR
  max_lr: 0.0005
  pct_start: 0.1
  # steps_per_epoch: ${trainer.epoch_len}
  epochs: ${trainer.n_epochs}
  anneal_strategy: cos

loss_function:
  _target_: src.loss.BPRLoss

trainer:
  log_step: 2000
  n_epochs: 1
  # epoch_len: null
  device_tensors: ["user", "double_user", "dt_emb", "item_pos", "double_item_pos", "kt_emb_pos", "item_neg", "double_item_neg", "kt_emb_neg"] # which tensors should be on device (ex. GPU)
  resume_from: null # null or path to the checkpoint dir with *.pth and config.yaml
  device: auto # device name or "auto"
  override: True # if True, will override the previous run with the same name
  monitor: "min val_loss" # "off" or "max/min metric_name", i.e. our goal is to maximize/minimize metric
  save_period: 1 # checkpoint each save_period epochs in addition to the best epoch
  early_stop: ${trainer.n_epochs} # epochs for early stopping
  save_dir: "deepfm_logs" # directory to save logs and checkpoints
  seed: 1
  max_grad_norm: 8
  # TODO: maybe add max_grad_norm
