_target_: src.logger.TensorboardWriter
project_name: "retail_testing" #менять через writer.project_name="..."
entity: null
run_name: "testing" # менять через writer.run_name="..."
mode: "online"
loss_names: ["loss"] # which losses to log (useful for multi-loss tasks, s.a. GANs)
log_checkpoints: False # set to True if you want to log save_dir with checkpoints to W&B
id_length: 8 # length of the run_id
